module.exports = {
    '1': { 'name': 'Amerika Serikat', 'flag': '🇺🇸' },
    '7': { 'name': 'Rusia', 'flag': '🇷🇺' },
    '20': { 'name': 'Mesir', 'flag': '🇪🇬' },
    '27': { 'name': 'Afrika Selatan', 'flag': '🇿🇦' },
    '30': { 'name': 'Yunani', 'flag': '🇬🇷' },
    '31': { 'name': 'Belanda', 'flag': '🇳🇱' },
    '32': { 'name': 'Belgia', 'flag': '🇧🇪' },
    '33': { 'name': 'Prancis', 'flag': '🇫🇷' },
    '34': { 'name': 'Spanyol', 'flag': '🇪🇸' },
    '36': { 'name': 'Hungaria', 'flag': '🇭🇺' },
    '39': { 'name': 'Italia', 'flag': '🇮🇹' },
    '40': { 'name': 'Rumania', 'flag': '🇷🇴' },
    '41': { 'name': 'Swiss', 'flag': '🇨🇭' },
    '43': { 'name': 'Austria', 'flag': '🇦🇹' },
    '44': { 'name': 'Inggris', 'flag': '🇬🇧' },
    '45': { 'name': 'Denmark', 'flag': '🇩🇰' },
    '46': { 'name': 'Swedia', 'flag': '🇸🇪' },
    '47': { 'name': 'Norwegia', 'flag': '🇳🇴' },
    '48': { 'name': 'Polandia', 'flag': '🇵🇱' },
    '49': { 'name': 'Jerman', 'flag': '🇩🇪' },
    '51': { 'name': 'Peru', 'flag': '🇵🇪' },
    '52': { 'name': 'Meksiko', 'flag': '🇲🇽' },
    '53': { 'name': 'Kuba', 'flag': '🇨🇺' },
    '54': { 'name': 'Argentina', 'flag': '🇦🇷' },
    '55': { 'name': 'Brasil', 'flag': '🇧🇷' },
    '56': { 'name': 'Chili', 'flag': '🇨🇱' },
    '57': { 'name': 'Kolombia', 'flag': '🇨🇴' },
    '58': { 'name': 'Venezuela', 'flag': '🇻🇪' },
    '60': { 'name': 'Malaysia', 'flag': '🇲🇾' },
    '61': { 'name': 'Australia', 'flag': '🇦🇺' },
    '62': { 'name': 'Indonesia', 'flag': '🇮🇩' },
    '63': { 'name': 'Filipina', 'flag': '🇵🇭' },
    '64': { 'name': 'Selandia Baru', 'flag': '🇳🇿' },
    '65': { 'name': 'Singapura', 'flag': '🇸🇬' },
    '66': { 'name': 'Thailand', 'flag': '🇹🇭' },
    '81': { 'name': 'Jepang', 'flag': '🇯🇵' },
    '82': { 'name': 'Korea Selatan', 'flag': '🇰🇷' },
    '84': { 'name': 'Vietnam', 'flag': '🇻🇳' },
    '86': { 'name': 'China', 'flag': '🇨🇳' },
    '90': { 'name': 'Turki', 'flag': '🇹🇷' },
    '91': { 'name': 'India', 'flag': '🇮🇳' },
    '92': { 'name': 'Pakistan', 'flag': '🇵🇰' },
    '93': { 'name': 'Afganistan', 'flag': '🇦🇫' },
    '94': { 'name': 'Sri Lanka', 'flag': '🇱🇰' },
    '95': { 'name': 'Myanmar', 'flag': '🇲🇲' },
    '98': { 'name': 'Iran', 'flag': '🇮🇷' },
    '160': { 'name': 'Guam', 'flag': '🇬🇺' },
    '164': { 'name': 'Saint Kitts dan Nevis', 'flag': '🇰🇳' },
    '183': { 'name': 'Kepulauan Mariana Utara', 'flag': '🇲🇵' },
    '187': { 'name': 'Republik Dominika', 'flag': '🇩🇴' },
    '211': { 'name': 'Sudan Selatan', 'flag': '🇸🇸' },
    '212': { 'name': 'Maroko', 'flag': '🇲🇦' },
    '213': { 'name': 'Aljazair', 'flag': '🇩🇿' },
    '216': { 'name': 'Tunisia', 'flag': '🇹🇳' },
    '218': { 'name': 'Libya', 'flag': '🇱🇾' },
    '220': { 'name': 'Gambia', 'flag': '🇬🇲' },
    '221': { 'name': 'Senegal', 'flag': '🇸🇳' },
    '222': { 'name': 'Mauritania', 'flag': '🇲🇷' },
    '223': { 'name': 'Mali', 'flag': '🇲🇱' },
    '224': { 'name': 'Guinea', 'flag': '🇬🇳' },
     '225': { 'name': 'Pantai Gading', 'flag': '🇨🇮' },
    '226': { 'name': 'Burkina Faso', 'flag': '🇧🇫' },
    '227': { 'name': 'Niger', 'flag': '🇳🇪' },
    '228': { 'name': 'Togo', 'flag': '🇹🇬' },
    '229': { 'name': 'Benin', 'flag': '🇧🇯' },
    '230': { 'name': 'Mauritius', 'flag': '🇲🇺' },
    '231': { 'name': 'Liberia', 'flag': '🇱🇷' },
    '232': { 'name': 'Sierra Leone', 'flag': '🇸🇱' },
    '233': { 'name': 'Ghana', 'flag': '🇬🇭' },
    '234': { 'name': 'Nigeria', 'flag': '🇳🇬' },
    '235': { 'name': 'Chad', 'flag': '🇹🇩' },
    '236': { 'name': 'Republik Afrika Tengah', 'flag': '🇨🇫' },
    '237': { 'name': 'Kamerun', 'flag': '🇨🇲' },
    '238': { 'name': 'Tanjung Verde', 'flag': '🇨🇻' },
    '239': { 'name': 'Sao Tome dan Principe', 'flag': '🇸🇹' },
    '240': { 'name': 'Guinea Khatulistiwa', 'flag': '🇬🇶' },
    '241': { 'name': 'Gabon', 'flag': '🇬🇦' },
    '242': { 'name': 'Republik Kongo', 'flag': '🇨🇬' },
    '243': { 'name': 'Republik Demokratik Kongo', 'flag': '🇨🇩' },
    '244': { 'name': 'Angola', 'flag': '🇦🇴' },
    '245': { 'name': 'Guinea-Bissau', 'flag': '🇬🇼' },
    '246': { 'name': 'Diego Garcia', 'flag': '🇩🇬' },
    '247': { 'name': 'Pulau Ascension', 'flag': '🇦🇨' },
    '248': { 'name': 'Seychelles', 'flag': '🇸🇨' },
    '249': { 'name': 'Sudan', 'flag': '🇸🇩' },
    '250': { 'name': 'Rwanda', 'flag': '🇷🇼' },
    '251': { 'name': 'Ethiopia', 'flag': '🇪🇹' },
    '252': { 'name': 'Somalia', 'flag': '🇸🇴' },
    '253': { 'name': 'Djibouti', 'flag': '🇩🇯' },
    '254': { 'name': 'Kenya', 'flag': '🇰🇪' },
    '255': { 'name': 'Tanzania', 'flag': '🇹🇿' },
    '256': { 'name': 'Uganda', 'flag': '🇺🇬' },
    '257': { 'name': 'Burundi', 'flag': '🇧🇮' },
    '258': { 'name': 'Mozambik', 'flag': '🇲🇿' },
    '260': { 'name': 'Zambia', 'flag': '🇿🇲' },
    '261': { 'name': 'Madagaskar', 'flag': '🇲🇬' },
    '263': { 'name': 'Zimbabwe', 'flag': '🇿🇼' },
    '264': { 'name': 'Namibia', 'flag': '🇳🇦' },
    '265': { 'name': 'Malawi', 'flag': '🇲🇼' },
    '266': { 'name': 'Lesotho', 'flag': '🇱🇸' },
    '267': { 'name': 'Botswana', 'flag': '🇧🇼' },
    '268': { 'name': 'Eswatini', 'flag': '🇸🇿' },
    '269': { 'name': 'Komoro', 'flag': '🇰🇲' },
    '290': { 'name': 'Saint Helena', 'flag': '🇸🇭' },
    '291': { 'name': 'Eritrea', 'flag': '🇪🇷' },
    '297': { 'name': 'Aruba', 'flag': '🇦🇼' },
    '298': { 'name': 'Kepulauan Faroe', 'flag': '🇫🇴' },
    '299': { 'name': 'Greenland', 'flag': '🇬🇱' },
    '355': { 'name': 'Albania', 'flag': '🇦🇱' },
    '371': { 'name': 'Latvia', 'flag': '🇱🇻' },
    '372': { 'name': 'Estonia', 'flag': '🇪🇪' },
    '373': { 'name': 'Moldova', 'flag': '🇲🇩' },
    '374': { 'name': 'Armenia', 'flag': '🇦🇲' },
    '375': { 'name': 'Belarus', 'flag': '🇧🇾' },
    '376': { 'name': 'Andorra', 'flag': '🇦🇩' },
    '377': { 'name': 'Monako', 'flag': '🇲🇨' },
    '378': { 'name': 'San Marino', 'flag': '🇸🇲' },
    '380': { 'name': 'Ukraina', 'flag': '🇺🇦' },
    '381': { 'name': 'Serbia', 'flag': '🇷🇸' },
    '382': { 'name': 'Montenegro', 'flag': '🇲🇪' },
     '383': { 'name': 'Kosovo', 'flag': '🇽🇰' },
    '385': { 'name': 'Kroasia', 'flag': '🇭🇷' },
    '386': { 'name': 'Slovenia', 'flag': '🇸🇮' },
    '387': { 'name': 'Bosnia dan Herzegovina', 'flag': '🇧🇦' },
    '389': { 'name': 'Makedonia Utara', 'flag': '🇲🇰' },
    '502': { 'name': 'Guatemala', 'flag': '🇬🇹' },
    '505': { 'name': 'Australia (Darwin)', 'flag': '🇦🇺' },
    '507': { 'name': 'Panama', 'flag': '🇵🇦' },
    '509': { 'name': 'Haiti', 'flag': '🇭🇹' },
    '670': { 'name': 'Timor Leste', 'flag': '🇹🇱' },
    '672': { 'name': 'Antartika', 'flag': '🇦🇶' },
    '673': { 'name': 'Brunei', 'flag': '🇧🇳' },
    '674': { 'name': 'Nauru', 'flag': '🇳🇷' },
    '675': { 'name': 'Papua Nugini', 'flag': '🇵🇬' },
    '676': { 'name': 'Tonga', 'flag': '🇹🇴' },
    '677': { 'name': 'Kepulauan Solomon', 'flag': '🇸🇧' },
    '678': { 'name': 'Vanuatu', 'flag': '🇻🇺' },
    '679': { 'name': 'Fiji', 'flag': '🇫🇯' },
    '680': { 'name': 'Palau', 'flag': '🇵🇼' },
    '681': { 'name': 'Wallis dan Futuna', 'flag': '🇼🇫' },
    '682': { 'name': 'Kepulauan Cook', 'flag': '🇨🇰' },
    '683': { 'name': 'Niue', 'flag': '🇳🇺' },
    '685': { 'name': 'Samoa', 'flag': '🇼🇸' },
    '686': { 'name': 'Kiribati', 'flag': '🇰🇮' },
    '687': { 'name': 'Kaledonia Baru', 'flag': '🇳🇨' },
    '688': { 'name': 'Tuvalu', 'flag': '🇹🇻' },
    '689': { 'name': 'Polinesia Prancis', 'flag': '🇵🇫' },
    '690': { 'name': 'Tokelau', 'flag': '🇹🇰' },
    '691': { 'name': 'Mikronesia', 'flag': '🇫🇲' },
    '692': { 'name': 'Kepulauan Marshall', 'flag': '🇲🇭' },
    '850': { 'name': 'Korea Utara', 'flag': '🇰🇵' },
    '856': { 'name': 'Laos', 'flag': '🇱🇦' },
    '880': { 'name': 'Bangladesh', 'flag': '🇧🇩' },
    '886': { 'name': 'Taiwan', 'flag': '🇹🇼' },
    '960': { 'name': 'Maladewa', 'flag': '🇲🇻' },
    '961': { 'name': 'Lebanon', 'flag': '🇱🇧' },
    '962': { 'name': 'Yordania', 'flag': '🇯🇴' },
    '963': { 'name': 'Suriah', 'flag': '🇸🇾' },
    '964': { 'name': 'Irak', 'flag': '🇮🇶' },
    '965': { 'name': 'Kuwait', 'flag': '🇰🇼' },
    '966': { 'name': 'Arab Saudi', 'flag': '🇸🇦' },
    '967': { 'name': 'Yaman', 'flag': '🇾🇪' },
    '968': { 'name': 'Oman', 'flag': '🇴🇲' },
    '970': { 'name': 'Palestina', 'flag': '🇵🇸' },
    '971': { 'name': 'Uni Emirat Arab', 'flag': '🇦🇪' },
    '972': { 'name': 'Israel', 'flag': '🇮🇱' },
    '973': { 'name': 'Bahrain', 'flag': '🇧🇭' },
    '974': { 'name': 'Qatar', 'flag': '🇶🇦' },
    '975': { 'name': 'Bhutan', 'flag': '🇧🇹' },
    '976': { 'name': 'Mongolia', 'flag': '🇲🇳' },
    '977': { 'name': 'Nepal', 'flag': '🇳🇵' },
    '995': { 'name': 'Georgia', 'flag': '🇬🇪' },
    '996': { 'name': 'Kirgistan', 'flag': '🇰🇬' },
    '998': { 'name': 'Uzbekistan', 'flag': '🇺🇿' },
    '855': { 'name': 'Kamboja', 'flag': '🇰🇭' },
    '994': { 'name': 'Azerbaijan', 'flag': '🇦🇿' },
    '358': { 'name': 'Finlandia', 'flag': '🇫🇮' },
    '792': { 'name': 'Rusia (Moskow)', 'flag': '🇷🇺' },
    '852': { 'name': 'Hong Kong', 'flag': '🇭🇰' },
    '870': { 'name': 'Inmarsat (Satelit Global)', 'flag': '🌍' }
};
